<?php
namespace services;
use services\AmoCrmAuthTrite;

class AmoCrmConnectAbstract
{
    use AmoCrmAuthTrite;

    public function __construct()
    {
        $this->accessToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImU2N2JhM2IzNDBhYzE0MmE0ZjIyMWMwYjczNzUxNmRkZDU5YzBiMjQ2MTdkZDEyMmY0MmJhYjgyNDNmODlkZjgzYTM2NWMxNDQ1MGE3MWRkIn0.eyJhdWQiOiJlZGVmZTFiMy1iYWY3LTQyYWYtODk5Yy01MDYyMWViMjc1YjAiLCJqdGkiOiJlNjdiYTNiMzQwYWMxNDJhNGYyMjFjMGI3Mzc1MTZkZGQ1OWMwYjI0NjE3ZGQxMjJmNDJiYWI4MjQzZjg5ZGY4M2EzNjVjMTQ0NTBhNzFkZCIsImlhdCI6MTcxNzA0Njk5MiwibmJmIjoxNzE3MDQ2OTkyLCJleHAiOjE3MjIzODQwMDAsInN1YiI6IjExMDg3MzUwIiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMxNzY4NDI2LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJjcm0iLCJmaWxlcyIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiLCJwdXNoX25vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiYjIzYWZlYjYtYjE4MC00NmVkLTg5NjEtMzhjZDBkYjcxODFkIn0.SNObMQ7GLTKn56PGAchJjqsICYImE3wP-6I2pqpCvbSUlthdHTliagHGF3ZqtuM5Y92HyHDmQdCjzk-sqH5yoCrSXooqiMwljtWMGO-KKDXydUEu2m8bqbnINizzVbaW7xyzzE8y4LsjR8O1DvytttaM_K0j_j7u3TT789DGTB-IjmtkLFqhmv_llDGofA2OmRnX786WlNxcC8WQ3lsAuW-QF-QEMZeuTWvDoOf8PyMW3WjfhyVonfYnmAh9hIgIUW2N4cBaIUNJmvdc0DTIS8zb4CCLP1v4X0lkqcJHls5Qwz5oFCrCHbqMf_qsRi08dwpvHGkVGS5GhZ2CPhWiSA';
        $this->subdomain = 'emfitestmailru';
    }
}