<?php
namespace services;
use services\AmoCrmAuthTrite;

class AmoCrmConnectAbstract
{
    use AmoCrmAuthTrite;

    public function __construct()
    {
        $this->accessToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjcyNTE1MDE0YmNhYTA1NDFjNjgwZDhkODYwNjYzODZmMTk2MDNmMGUxZmFlNmMwZWE0Zjk4Y2Y4Yzg3MmUzZTY4NmM0ZjI1NjU2NGM4MjNiIn0.eyJhdWQiOiJlZGVmZTFiMy1iYWY3LTQyYWYtODk5Yy01MDYyMWViMjc1YjAiLCJqdGkiOiI3MjUxNTAxNGJjYWEwNTQxYzY4MGQ4ZDg2MDY2Mzg2ZjE5NjAzZjBlMWZhZTZjMGVhNGY5OGNmOGM4NzJlM2U2ODZjNGYyNTY1NjRjODIzYiIsImlhdCI6MTcxNzAzMTk1NSwibmJmIjoxNzE3MDMxOTU1LCJleHAiOjE3MTk3MDU2MDAsInN1YiI6IjExMDg3MzUwIiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMxNzY4NDI2LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJjcm0iLCJmaWxlcyIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiLCJwdXNoX25vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiZDA4NjkyNWItNmQwZi00OWMxLTllNGYtYzc1MWE1NTk2NDYwIn0.qhxJivfWThnQ_PzdtACIA46WPCNbazrKRU7Py8FKdI3IhtkPbtFGrmzcbpvzzuUwyu8QTUDSkql3xBniTYd-c4wdjxLI2aqp3bKdRzfjqG8BQb6UOyL3tqA1ATvweTuxLcUagmRMVykWAHYeIi_Kw1l1hhlvlBRu8oB1Zgb76k_-NN8pxV5-ExdL0UlaWEQgz5bjqoJoRs5SfCe6QRmK-seaHEeRE9-if2rEY4Sk9uD2X5nwFPswX8Ya1R_w6FCC6X4s8Q89BqpchODWB1kPYPfKs5v_u11Y1pXeQrEXQMGkFA5OiTJlRtCgcCNYvOGHzFrgnPJAPPH6PVujJSrdNQ';
        $this->subdomain = 'emfitestmailru';
    }
}